// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication4.Models;

namespace WebApplication4.Models.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    partial class AplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication4.Models.Cliente", b =>
                {
                    b.Property<int>("IdCli")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contrato");

                    b.Property<string>("Cpf");

                    b.Property<DateTime>("Data");

                    b.Property<string>("Nome");

                    b.Property<decimal>("Valor_atualizado");

                    b.Property<decimal>("Valor_principal");

                    b.HasKey("IdCli");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("WebApplication4.Models.Debito", b =>
                {
                    b.Property<int>("IdDeb")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Dias");

                    b.Property<decimal>("Juros");

                    b.Property<decimal>("Multa");

                    b.Property<decimal>("Valor_final");

                    b.Property<decimal>("Valor_inicial");

                    b.Property<DateTime>("Vencimento");

                    b.HasKey("IdDeb");

                    b.ToTable("Debito");
                });

            modelBuilder.Entity("WebApplication4.Models.Pagamento", b =>
                {
                    b.Property<int>("IdPagto")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contrato");

                    b.Property<string>("Cpf");

                    b.Property<DateTime>("Data");

                    b.Property<int>("IdCli");

                    b.Property<int>("Parcela");

                    b.Property<string>("Situacao");

                    b.Property<decimal>("Valor");

                    b.HasKey("IdPagto");

                    b.HasIndex("IdCli");

                    b.ToTable("Pagamento");
                });

            modelBuilder.Entity("WebApplication4.Models.Pagamento", b =>
                {
                    b.HasOne("WebApplication4.Models.Cliente", "Cliente")
                        .WithMany("Pagamentos")
                        .HasForeignKey("IdCli")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
